apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ubuntu-service/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mlflow
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mlflow
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ubuntu-service/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/kompose-mlflow-default: "true"
        io.kompose.service: mlflow
    spec:
      containers:
        - args:
            - mlflow
            - server
            - --host
            - 0.0.0.0
            - --port
            - "5000"
          env:
            - name: MLFLOW_SQLALCHEMYSTORE_DATABASE_URI
              value: postgresql://mlflow:mlflow@postgres:5432/mlflow
          image: ashwinakannan/mlflow:1.0
          name: mlflow
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
